apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend-app
      app: dice
  template:
    metadata:
      labels: Project-backend-app
        tier: backend-app
        app: dice
    spec:
      containers:
      - name: backend-app
        image: mihmood/backend-app:1.4
        ports:
        - containerPort: 8080
          name: tcp

---
apiVersion: v1
kind: Service
metadata:
  name: backend-app
spec:
  selector:
    tier: backend-app
    app: dice
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 8080
